Repository JECT-Study/JECT-4-server, pull requests merged in 2025-07, with the labels that each got.

#18 chore: 테스트용 Base 클래스 및 워크플로우 .env 구성(#17)
  .github/workflows/develop_pull_request.yml
  src/test/java/com/ject/studytrip/BaseIntegrationTest.java
  src/test/java/com/ject/studytrip/BaseUnitTest.java
Labels: ⚙️chore

#26 refactor: MemberCategory 변환 및 Member 도메인 검증 로직 분리(#25)
  src/main/java/com/ject/studytrip/auth/application/facade/AuthFacade.java
  src/main/java/com/ject/studytrip/member/application/service/MemberService.java
  src/main/java/com/ject/studytrip/member/domain/entity/MemberCategory.java
  src/main/java/com/ject/studytrip/member/domain/error/MemberErrorCode.java
  src/main/java/com/ject/studytrip/member/domain/model/Member.java
  src/main/java/com/ject/studytrip/member/domain/model/MemberCategory.java
  src/main/java/com/ject/studytrip/member/domain/model/MemberRole.java
  src/main/java/com/ject/studytrip/member/domain/model/SocialProvider.java
  src/main/java/com/ject/studytrip/member/domain/policy/MemberPolicy.java
  src/main/java/com/ject/studytrip/member/domain/repository/MemberRepository.java
  src/main/java/com/ject/studytrip/member/factory/MemberFactory.java
  src/main/java/com/ject/studytrip/member/infra/jpa/MemberJpaRepository.java
  src/main/java/com/ject/studytrip/member/infra/jpa/MemberRepositoryAdapter.java
  src/main/java/com/ject/studytrip/trip/application/facade/TripFacade.java
  src/main/java/com/ject/studytrip/trip/application/service/TripService.java
  src/main/java/com/ject/studytrip/trip/domain/factory/TripFactory.java
  src/main/java/com/ject/studytrip/trip/domain/model/Trip.java
  src/test/java/com/ject/studytrip/member/application/service/MemberServiceTest.java
  src/test/java/com/ject/studytrip/member/fixture/MemberFixture.java
  src/test/java/com/ject/studytrip/member/helper/MemberTestHelper.java
  src/test/java/com/ject/studytrip/stamp/application/service/StampServiceTest.java
  src/test/java/com/ject/studytrip/trip/application/service/TripServiceTest.java
  src/test/java/com/ject/studytrip/trip/fixture/TripFixture.java
  src/test/java/com/ject/studytrip/trip/helper/TripTestHelper.java
  src/test/java/com/ject/studytrip/trip/presentation/controller/TripControllerIntegrationTest.java
Labels: 🪄refactor

#27 feat: 미션, 학습기록, 데일리 미션, 데일리 목표 도메인 엔티티 생성(#24)
  src/main/java/com/ject/studytrip/mission/domain/model/DailyMission.java
  src/main/java/com/ject/studytrip/mission/domain/model/Mission.java
  src/main/java/com/ject/studytrip/studylog/domain/model/StudyLog.java
  src/main/java/com/ject/studytrip/trip/domain/model/DailyGoal.java
Labels: ✨feature

#29 feat: 스탬프 기능 구현(#23)
  src/main/java/com/ject/studytrip/mission/application/dto/MissionInfo.java
  src/main/java/com/ject/studytrip/mission/application/service/MissionService.java
  src/main/java/com/ject/studytrip/mission/domain/repository/MissionRepository.java
  src/main/java/com/ject/studytrip/mission/infra/jpa/MissionJpaRepository.java
  src/main/java/com/ject/studytrip/mission/infra/jpa/MissionRepositoryAdapter.java
  src/main/java/com/ject/studytrip/mission/presentation/dto/response/LoadMissionInfoResponse.java
  src/main/java/com/ject/studytrip/stamp/application/dto/StampDetail.java
  src/main/java/com/ject/studytrip/stamp/application/facade/StampFacade.java
  src/main/java/com/ject/studytrip/stamp/application/service/StampService.java
  src/main/java/com/ject/studytrip/stamp/domain/error/StampErrorCode.java
  src/main/java/com/ject/studytrip/stamp/domain/model/Stamp.java
  src/main/java/com/ject/studytrip/stamp/domain/policy/StampPolicy.java
  src/main/java/com/ject/studytrip/stamp/domain/repository/StampQueryRepository.java
  src/main/java/com/ject/studytrip/stamp/domain/repository/StampRepository.java
  src/main/java/com/ject/studytrip/stamp/infra/jpa/StampJpaRepository.java
  src/main/java/com/ject/studytrip/stamp/infra/jpa/StampQueryRepositoryAdapter.java
  src/main/java/com/ject/studytrip/stamp/infra/jpa/StampRepositoryAdapter.java
  src/main/java/com/ject/studytrip/stamp/presentation/controller/StampController.java
  src/main/java/com/ject/studytrip/stamp/presentation/dto/request/UpdateStampNameAndDeadlineRequest.java
  src/main/java/com/ject/studytrip/stamp/presentation/dto/request/UpdateStampOrderRequest.java
  src/main/java/com/ject/studytrip/stamp/presentation/dto/response/CreateStampResponse.java
  src/main/java/com/ject/studytrip/stamp/presentation/dto/response/LoadStampDetailResponse.java
  src/main/java/com/ject/studytrip/stamp/presentation/dto/response/LoadStampInfoResponse.java
  src/main/java/com/ject/studytrip/trip/application/service/TripService.java
  src/main/java/com/ject/studytrip/trip/domain/model/Trip.java
  src/main/java/com/ject/studytrip/trip/domain/policy/TripPolicy.java
  src/main/java/com/ject/studytrip/trip/presentation/dto/response/LoadTripDetailResponse.java
  src/test/java/com/ject/studytrip/stamp/application/service/StampServiceTest.java
  src/test/java/com/ject/studytrip/stamp/fixture/StampFixture.java
  src/test/java/com/ject/studytrip/stamp/fixture/UpdateStampRequestFixture.java
  src/test/java/com/ject/studytrip/stamp/helper/StampTestHelper.java
  src/test/java/com/ject/studytrip/stamp/presentation/controller/StampControllerIntegrationTest.java
  src/test/java/com/ject/studytrip/trip/application/service/TripServiceTest.java
  src/test/java/com/ject/studytrip/trip/fixture/TripFixture.java
Labels: ✨feature

#36 fix: cors 에러 해결(#35)
  src/main/java/com/ject/studytrip/global/config/WebSecurityConfig.java
Labels: 🐛bug

#34 feat: 미션 기능 구현(#32)
  src/main/java/com/ject/.DS_Store
  src/main/java/com/ject/studytrip/mission/application/facade/MissionFacade.java
  src/main/java/com/ject/studytrip/mission/application/service/MissionService.java
  src/main/java/com/ject/studytrip/mission/domain/error/MissionErrorCode.java
  src/main/java/com/ject/studytrip/mission/domain/factory/MissionFactory.java
  src/main/java/com/ject/studytrip/mission/domain/model/Mission.java
  src/main/java/com/ject/studytrip/mission/domain/policy/MissionPolicy.java
  src/main/java/com/ject/studytrip/mission/domain/repository/MissionRepository.java
  src/main/java/com/ject/studytrip/mission/infra/jpa/MissionJpaRepository.java
  src/main/java/com/ject/studytrip/mission/infra/jpa/MissionRepositoryAdapter.java
  src/main/java/com/ject/studytrip/mission/presentation/controller/MissionController.java
  src/main/java/com/ject/studytrip/mission/presentation/dto/request/CreateMissionRequest.java
  src/main/java/com/ject/studytrip/mission/presentation/dto/request/UpdateMissionOrderRequest.java
  src/main/java/com/ject/studytrip/mission/presentation/dto/request/UpdateMissionRequest.java
  src/main/java/com/ject/studytrip/mission/presentation/dto/response/CreateMissionResponse.java
  src/main/java/com/ject/studytrip/stamp/application/facade/StampFacade.java
  src/main/java/com/ject/studytrip/stamp/application/service/StampService.java
  src/main/java/com/ject/studytrip/trip/application/facade/TripFacade.java
  src/test/java/com/ject/.DS_Store
  src/test/java/com/ject/studytrip/mission/application/service/MissionServiceTest.java
  src/test/java/com/ject/studytrip/mission/fixture/CreateMissionRequestFixture.java
  src/test/java/com/ject/studytrip/mission/fixture/MissionFixture.java
  src/test/java/com/ject/studytrip/mission/fixture/UpdateMissionOrderRequestFixture.java
  src/test/java/com/ject/studytrip/mission/fixture/UpdateMissionRequestFixture.java
  src/test/java/com/ject/studytrip/mission/helper/MissionTestHelper.java
  src/test/java/com/ject/studytrip/mission/presentation/controller/MissionControllerIntegrationTest.java
  src/test/java/com/ject/studytrip/stamp/application/service/StampServiceTest.java
Labels: ✨feature

#42 fix: 로컬 클라이언트 도메인 포트 5173으로 변경(#41)
  src/main/java/com/ject/studytrip/global/common/constants/UrlConstants.java
Labels: 🐛bug
